# Real MySQL Database settings
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# JPA settings for Production
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false